name: Deploy BCSS Notify Lambdas

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        options:
          - dev
  push:
    paths:
      - "batch_notification_processor/**"
      - "message_status_handler/**"
      - "shared/**"
      - "Pipfile"
      - "Pipfile.lock"
    branches: [main]

jobs:
  deploy-bcss-notify-lambdas:
    name: "Deploy lambdas and layers"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730319765130:role/bcss-github-actions-lambda-access
          aws-region: eu-west-2
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create zip file for packages layer
        run: |
          pip install pipenv
          mkdir -p python
          pipenv requirements > requirements.txt
          pipenv run pip install -r requirements.txt --target python/
          cd python
          find -name "tests" -type d | xargs rm -rf
          find -name "__pycache__" -type d | xargs rm -rf
          find -name "_pytest" -type d | xargs rm -rf
          cd ..
          zip -r layer.zip python/
      - name: Publish layer to AWS
        run: |
          aws lambda publish-layer-version \
            --layer-name bcss-comms-python-packages-dev \
            --zip-file fileb://layer.zip \
            --compatible-runtimes python3.13 \
            --region eu-west-2
      - name: Create zip file for Batch Notification Processor function
        run: cd batch_notification_processor && cp ../shared/*.py . && zip -r code.zip .
      - name: Update Batch Notification Processor lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-west-2:730319765130:function:bcss-comms-batch-notification-processor-dev \
            --zip-file fileb://batch_notification_processor/code.zip \
            --region eu-west-2
      - name: Create zip file for Message Status Handler function
        run: cd message_status_handler && cp ../shared/*.py . && zip -r code.zip .
      - name: Update Message Status Handler lambda function code
        run: |
          aws lambda update-function-code \
            --function-name arn:aws:lambda:eu-west-2:730319765130:function:bcss-comms-message-status-handler-dev \
            --zip-file fileb://message_status_handler/code.zip \
            --region eu-west-2
