name: "Secret scanning stage"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened]

jobs:
  set-up-dependencies:
    name: "Set up dependencies"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip

  Scan-secrets:
    name: "Scan secrets"
    needs: set-up-dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: "Scan secrets"
        shell: bash
        run: |
          # Please do not change this `check=whole-history` setting, as new patterns may be added or history may be rewritten.
          check=whole-history ./scripts/scan-secrets.sh
